### ISSUE TITLE
Some grammar constructions lack terminal lexemes

### ISSUE THREAD

**Issue by cyberone** [upwork/donkey-core#1]
Some grammar constructions lack terminal lexemes. This causes parser to capture part of next syntax construction. E.g.
```
import namespace com.company.package
import namespace php Company.Package
```
will create AST node ``namespaceImport`` with language: `com.company.package` and namespaceName: `import namespace`

**Comment by cyberone** [comment]
@lcf Please review #2

**Comment by lcf** [comment]
merged it, thanks
